name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          exclude: './third_party ./external ./include'
          extensions: 'h,c'
          clangFormatVersion: 9
          style: google

      - name: Get cmake
        uses: lukka/get-cmake@v3.19.2

      - name: Install packages
        run: sudo apt update install make clang-format-9 pkg-config g++ autoconf libtool asciidoctor libkmod-dev libudev-dev uuid-dev libjson-c-dev libkeyutils-dev pandoc libhwloc-dev libgflags-dev libtext-diff-perl bash-completion systemd wget git -y

      - name: Install ndctl
        run: |
          cd /tmp; git clone https://github.com/pmem/ndctl.git; cd ndctl; git checkout v70.1
          ./autogen.sh; ./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib
          make -j && sudo make install

      - name: Install pmdk
        run: |
          cd /tmp; git clone https://github.com/pmem/pmdk.git; cd pmdk; git checkout 1.11.1
          make -j && sudo make install

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          bash build.sh

